// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/eventstore.proto

package eventstorepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_DIRECTION_FORWARDS  Direction = 0
	Direction_DIRECTION_BACKWARDS Direction = 1
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_FORWARDS",
		1: "DIRECTION_BACKWARDS",
	}
	Direction_value = map[string]int32{
		"DIRECTION_FORWARDS":  0,
		"DIRECTION_BACKWARDS": 1,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_eventstore_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_proto_eventstore_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_proto_eventstore_proto_rawDescGZIP(), []int{0}
}

// Event is a stored event as returned by reads.
type Event struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StreamName     string                 `protobuf:"bytes,1,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	EventType      string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Position       uint64                 `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`                                   // 1-based position within its stream
	GlobalPosition uint64                 `protobuf:"varint,4,opt,name=global_position,json=globalPosition,proto3" json:"global_position,omitempty"` // position within the whole store
	Timestamp      uint64                 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                 // unix nanoseconds, assigned by the server
	Payload        []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Meta           []byte                 `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_eventstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_eventstore_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetStreamName() string {
	if x != nil {
		return x.StreamName
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetPosition() uint64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Event) GetGlobalPosition() uint64 {
	if x != nil {
		return x.GlobalPosition
	}
	return 0
}

func (x *Event) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

// NewEvent is the client-supplied part of an event. The server assigns position,
// global position and (if unset) timestamp.
type NewEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Meta          []byte                 `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewEvent) Reset() {
	*x = NewEvent{}
	mi := &file_proto_eventstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEvent) ProtoMessage() {}

func (x *NewEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEvent.ProtoReflect.Descriptor instead.
func (*NewEvent) Descriptor() ([]byte, []int) {
	return file_proto_eventstore_proto_rawDescGZIP(), []int{1}
}

func (x *NewEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *NewEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NewEvent) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

type AppendRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StreamName string                 `protobuf:"bytes,1,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	// expected_version follows the store's OCC rules: -1 (AnyVersion) disables the
	// check; a value >= 0 requires the stream's current version to equal it exactly
	// (0 means the stream must not yet exist).
	ExpectedVersion int64       `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	Events          []*NewEvent `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_proto_eventstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventstore_proto_rawDescGZIP(), []int{2}
}

func (x *AppendRequest) GetStreamName() string {
	if x != nil {
		return x.StreamName
	}
	return ""
}

func (x *AppendRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *AppendRequest) GetEvents() []*NewEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type AppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // the stream's new version after the append
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_proto_eventstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_proto_eventstore_proto_rawDescGZIP(), []int{3}
}

func (x *AppendResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ReadStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamName    string                 `protobuf:"bytes,1,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	From          uint64                 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`   // inclusive 1-based position; 0 means "from the natural start"
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // <= 0 means unbounded
	Direction     Direction              `protobuf:"varint,4,opt,name=direction,proto3,enum=eventstore.v1.Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStreamRequest) Reset() {
	*x = ReadStreamRequest{}
	mi := &file_proto_eventstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStreamRequest) ProtoMessage() {}

func (x *ReadStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStreamRequest.ProtoReflect.Descriptor instead.
func (*ReadStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventstore_proto_rawDescGZIP(), []int{4}
}

func (x *ReadStreamRequest) GetStreamName() string {
	if x != nil {
		return x.StreamName
	}
	return ""
}

func (x *ReadStreamRequest) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ReadStreamRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ReadStreamRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_FORWARDS
}

type ReadCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	From          uint64                 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`   // inclusive 1-based category-local position; 0 means "from the start"
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // <= 0 means unbounded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCategoryRequest) Reset() {
	*x = ReadCategoryRequest{}
	mi := &file_proto_eventstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCategoryRequest) ProtoMessage() {}

func (x *ReadCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eventstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCategoryRequest.ProtoReflect.Descriptor instead.
func (*ReadCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_eventstore_proto_rawDescGZIP(), []int{5}
}

func (x *ReadCategoryRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ReadCategoryRequest) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ReadCategoryRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_proto_eventstore_proto protoreflect.FileDescriptor

const file_proto_eventstore_proto_rawDesc = "" +
	"\n" +
	"\x16proto/eventstore.proto\x12\reventstore.v1\"\xd8\x01\n" +
	"\x05Event\x12\x1f\n" +
	"\vstream_name\x18\x01 \x01(\tR\n" +
	"streamName\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x04R\bposition\x12'\n" +
	"\x0fglobal_position\x18\x04 \x01(\x04R\x0eglobalPosition\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x04R\ttimestamp\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x12\n" +
	"\x04meta\x18\a \x01(\fR\x04meta\"W\n" +
	"\bNewEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x12\n" +
	"\x04meta\x18\x03 \x01(\fR\x04meta\"\x8c\x01\n" +
	"\rAppendRequest\x12\x1f\n" +
	"\vstream_name\x18\x01 \x01(\tR\n" +
	"streamName\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\x12/\n" +
	"\x06events\x18\x03 \x03(\v2\x17.eventstore.v1.NewEventR\x06events\"*\n" +
	"\x0eAppendResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\"\x96\x01\n" +
	"\x11ReadStreamRequest\x12\x1f\n" +
	"\vstream_name\x18\x01 \x01(\tR\n" +
	"streamName\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x04R\x04from\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x126\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x18.eventstore.v1.DirectionR\tdirection\"[\n" +
	"\x13ReadCategoryRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x04R\x04from\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit*<\n" +
	"\tDirection\x12\x16\n" +
	"\x12DIRECTION_FORWARDS\x10\x00\x12\x17\n" +
	"\x13DIRECTION_BACKWARDS\x10\x012\xe7\x01\n" +
	"\n" +
	"EventStore\x12E\n" +
	"\x06Append\x12\x1c.eventstore.v1.AppendRequest\x1a\x1d.eventstore.v1.AppendResponse\x12F\n" +
	"\n" +
	"ReadStream\x12 .eventstore.v1.ReadStreamRequest\x1a\x14.eventstore.v1.Event0\x01\x12J\n" +
	"\fReadCategory\x12\".eventstore.v1.ReadCategoryRequest\x1a\x14.eventstore.v1.Event0\x01B8Z6github.com/leow93/eventstore/eventstorepb;eventstorepbb\x06proto3"

var (
	file_proto_eventstore_proto_rawDescOnce sync.Once
	file_proto_eventstore_proto_rawDescData []byte
)

func file_proto_eventstore_proto_rawDescGZIP() []byte {
	file_proto_eventstore_proto_rawDescOnce.Do(func() {
		file_proto_eventstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_eventstore_proto_rawDesc), len(file_proto_eventstore_proto_rawDesc)))
	})
	return file_proto_eventstore_proto_rawDescData
}

var file_proto_eventstore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_eventstore_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_eventstore_proto_goTypes = []any{
	(Direction)(0),              // 0: eventstore.v1.Direction
	(*Event)(nil),               // 1: eventstore.v1.Event
	(*NewEvent)(nil),            // 2: eventstore.v1.NewEvent
	(*AppendRequest)(nil),       // 3: eventstore.v1.AppendRequest
	(*AppendResponse)(nil),      // 4: eventstore.v1.AppendResponse
	(*ReadStreamRequest)(nil),   // 5: eventstore.v1.ReadStreamRequest
	(*ReadCategoryRequest)(nil), // 6: eventstore.v1.ReadCategoryRequest
}
var file_proto_eventstore_proto_depIdxs = []int32{
	2, // 0: eventstore.v1.AppendRequest.events:type_name -> eventstore.v1.NewEvent
	0, // 1: eventstore.v1.ReadStreamRequest.direction:type_name -> eventstore.v1.Direction
	3, // 2: eventstore.v1.EventStore.Append:input_type -> eventstore.v1.AppendRequest
	5, // 3: eventstore.v1.EventStore.ReadStream:input_type -> eventstore.v1.ReadStreamRequest
	6, // 4: eventstore.v1.EventStore.ReadCategory:input_type -> eventstore.v1.ReadCategoryRequest
	4, // 5: eventstore.v1.EventStore.Append:output_type -> eventstore.v1.AppendResponse
	1, // 6: eventstore.v1.EventStore.ReadStream:output_type -> eventstore.v1.Event
	1, // 7: eventstore.v1.EventStore.ReadCategory:output_type -> eventstore.v1.Event
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_eventstore_proto_init() }
func file_proto_eventstore_proto_init() {
	if File_proto_eventstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_eventstore_proto_rawDesc), len(file_proto_eventstore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_eventstore_proto_goTypes,
		DependencyIndexes: file_proto_eventstore_proto_depIdxs,
		EnumInfos:         file_proto_eventstore_proto_enumTypes,
		MessageInfos:      file_proto_eventstore_proto_msgTypes,
	}.Build()
	File_proto_eventstore_proto = out.File
	file_proto_eventstore_proto_goTypes = nil
	file_proto_eventstore_proto_depIdxs = nil
}
