// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/eventstore.proto

package eventstorepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventStore_Append_FullMethodName       = "/eventstore.v1.EventStore/Append"
	EventStore_ReadStream_FullMethodName   = "/eventstore.v1.EventStore/ReadStream"
	EventStore_ReadCategory_FullMethodName = "/eventstore.v1.EventStore/ReadCategory"
)

// EventStoreClient is the client API for EventStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventStore exposes the single-node event store over gRPC. Reads use
// server-side streaming so large streams/categories are delivered incrementally.
type EventStoreClient interface {
	// Append writes events to a stream under optimistic-concurrency control.
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
	// ReadStream streams the events of a single stream, forwards or backwards.
	ReadStream(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// ReadCategory streams the events of a category in append order.
	ReadCategory(ctx context.Context, in *ReadCategoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type eventStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewEventStoreClient(cc grpc.ClientConnInterface) EventStoreClient {
	return &eventStoreClient{cc}
}

func (c *eventStoreClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, EventStore_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) ReadStream(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventStore_ServiceDesc.Streams[0], EventStore_ReadStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadStreamRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStore_ReadStreamClient = grpc.ServerStreamingClient[Event]

func (c *eventStoreClient) ReadCategory(ctx context.Context, in *ReadCategoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventStore_ServiceDesc.Streams[1], EventStore_ReadCategory_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadCategoryRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStore_ReadCategoryClient = grpc.ServerStreamingClient[Event]

// EventStoreServer is the server API for EventStore service.
// All implementations must embed UnimplementedEventStoreServer
// for forward compatibility.
//
// EventStore exposes the single-node event store over gRPC. Reads use
// server-side streaming so large streams/categories are delivered incrementally.
type EventStoreServer interface {
	// Append writes events to a stream under optimistic-concurrency control.
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	// ReadStream streams the events of a single stream, forwards or backwards.
	ReadStream(*ReadStreamRequest, grpc.ServerStreamingServer[Event]) error
	// ReadCategory streams the events of a category in append order.
	ReadCategory(*ReadCategoryRequest, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedEventStoreServer()
}

// UnimplementedEventStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventStoreServer struct{}

func (UnimplementedEventStoreServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedEventStoreServer) ReadStream(*ReadStreamRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method ReadStream not implemented")
}
func (UnimplementedEventStoreServer) ReadCategory(*ReadCategoryRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method ReadCategory not implemented")
}
func (UnimplementedEventStoreServer) mustEmbedUnimplementedEventStoreServer() {}
func (UnimplementedEventStoreServer) testEmbeddedByValue()                    {}

// UnsafeEventStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventStoreServer will
// result in compilation errors.
type UnsafeEventStoreServer interface {
	mustEmbedUnimplementedEventStoreServer()
}

func RegisterEventStoreServer(s grpc.ServiceRegistrar, srv EventStoreServer) {
	// If the following call panics, it indicates UnimplementedEventStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventStore_ServiceDesc, srv)
}

func _EventStore_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventStore_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_ReadStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStoreServer).ReadStream(m, &grpc.GenericServerStream[ReadStreamRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStore_ReadStreamServer = grpc.ServerStreamingServer[Event]

func _EventStore_ReadCategory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadCategoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStoreServer).ReadCategory(m, &grpc.GenericServerStream[ReadCategoryRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStore_ReadCategoryServer = grpc.ServerStreamingServer[Event]

// EventStore_ServiceDesc is the grpc.ServiceDesc for EventStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eventstore.v1.EventStore",
	HandlerType: (*EventStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _EventStore_Append_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadStream",
			Handler:       _EventStore_ReadStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadCategory",
			Handler:       _EventStore_ReadCategory_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/eventstore.proto",
}
